---
- name: Create group "nginx-exp"
  become: true
  group:
    name: nginx-exp
    state: present

- name: Add user nginx-exp to nginx-exp group
  become: true
  user:
    name: nginx-exp
    shell: /bin/bash
    groups: nginx-exp

- name: Download the nginx-exporter
  become: true
  get_url:
    url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.3.0/nginx-prometheus-exporter-0.3.0-linux-amd64.tar.gz
    dest: /tmp/nginx-prometheus-exporter-0.3.0-linux-amd64.tar.gz
    mode: 0550

- name: Unpack the nginx-prometheus-exporter-0.3.0-linux-amd64.tar.gz
  become: true
  unarchive:
    src: /tmp/nginx-prometheus-exporter-0.3.0-linux-amd64.tar.gz
    remote_src: true
    dest: /usr/local/bin/

- name: copy the nginx_exporter.service.j2 file from files folder
  become: true
  template:
    src: files/nginx_exporter.service.j2
    dest: /etc/systemd/system/nginx_exporter.service
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: 0644

- name: starting the nginx_exporter service
  become: true
  systemd:
    state: started
    name: nginx_exporter
