---
- name: when GET request to port 9113/metrics does not return nginx_up 1
  uri:
    url: http://localhost:9113/metrics
    return_content: true
  register: this
  failed_when: "'nginx_up 1' not in this.content"

- name: when GET request to port 80 does not return status code 200.
  uri:
    url: http://localhost
    status_code: 200
  register: this
  failed_when: False
