# -*- mode: ruby -*-
# vi: set ft=ruby :

# We are defining a new variable `HOSTNAME`
#HOSTNAME = "webserver.test"

# Create VM using Ansible Provider VirtualBox
#  config.vm.provider :virtualbox do |vb|
#    vb.name = HOSTNAME
#  end

# Variable 'node' to define webserver with hostname and IP address
nodes = [
  { :hostname => "webserver.test",    :ip => '10.100.0.2' },
]
Vagrant.configure("2") do |config|
  # Vagrant boxes allow anyone to package their environment into an image and
    # share it with others. See https://app.vagrantup.com/boxes/search.
  config.vm.box = "centos/7"

# By default, Vagrant will share your project directory to `/vagrant` inside
# the virtual machine. See https://www.vagrantup.com/docs/synced-folders/.
  config.vm.synced_folder ".", "/vagrant", disabled: true

# Configure new VM

  config.vm.network "forwarded_port", guest: 22, host: 50022
  config.vm.network "forwarded_port", guest: 80, host: 50080
  config.vm.provider  :virtualbox do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end
# Configure network for HOSTNAME
  nodes.each do |node|
    config.vm.define node[:hostname] do |nodeconfig|
      nodeconfig.vm.hostname = node[:hostname]
      nodeconfig.vm.network "private_network", ip: node[:ip]
    end
  end

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "site.yml"
  end
end
