---
  - become: true
    rpm_key:
      key: "{{ nginx_signing_key }}"

  - name: add nginx repository
    become: true
    yum_repository:
      name: nginx
      baseurl: "{{ nginx_base_repository }}"
      description: nginx repository
      enabled: true
      gpgcheck: yes

  - become: true
    package:
      name: nginx
      notify: start nginx

  - name: override default home page
    become: true
    copy:
      content: |
        <!DOCTYPE html>
        <html>
        <head>
          <title>Hello world.</title>
          <meta http-equiv="Content-Type" content="tenginx-exporterxt/html; charset=utf-8" />
          <style>body {font: normal 18px Arial; margin: 4em;}</style>
        </head>
        <body>
          <p>
          YAML supports multi-line blocks using specific indicators.<br />
          Read more at <a href="https://yaml-multiline.info">YAML-multiline.info</a>
          </p>
        </body>
        </html>
      dest: /usr/share/nginx/html/index.html

    - import_playbook: exporter.yml

    - name: Start and Enable nginx-exporter Service
      systemd:
        name: nginx-prometheus-exporter
        state: started
        enabled: True
