---
- hosts: all
  tasks:
    - name: install common tools
      # Certain tasks, such as installing system packages, require root
      # privileges. The following line allows you to 'become' another user, and
      # the value 'true' is a special case representing privilege escalation to
      # root.
      become: true
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - bind-utils
        - net-tools
        - vim
        - wget
