---
- hosts: all
  become: true
  vars:
    users: ['jpangilinan', 'nsmeds']

  tasks:
    - name: create users
      user:
        name: "{{ item }}"
        state: present
        group: wheel
        shell: /bin/bash
      with_items: "{{ users }}"

    - name: secure home directory
      file:
        path: /home/{{ item }}
        owner: "{{ item }}"
        mode: 0750
      with_items: "{{ users }}"

    - name: "Set authorized keys"
      authorized_key:
        user: "{{ item }}"
        state: present
        key: "{{ lookup('file', 'files/'+ item + '.pub') }}"
        path:  /home/{{ item }}/.ssh/authorized_keys
      with_items: "{{ users }}"

    - lineinfile:
        path: /etc/sudoers
        state: present
        line: '"{{ item }}" ALL=(ALL) NOPASSWD: ALL'
        mode: 0440
        validate: '/usr/sbin/visudo -cf %s'
      with_items: "{{ users }}"
